-- ==========================================
-- SCRIPT DE CONFIGURACIÓN PARA SUPABASE
-- Ejecutar este código en el SQL Editor de Supabase
-- ==========================================

-- 1. Tabla para la configuración del Flyer (Persistencia del Editor)
CREATE TABLE IF NOT EXISTS flyer_config (
    id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    developer_name text NOT NULL DEFAULT 'Enzo Girardi',
    role text NOT NULL DEFAULT 'Programador & Desarrollador de Software',
    hook_title text NOT NULL DEFAULT '¿LENTITUD EN TU NEGOCIO? MULTIPLICÁ TUS VENTAS HOY',
    slogan text NOT NULL DEFAULT 'Desarrollo programas a medida que automatizan tu gestión, eliminan errores y ordenan tus ventas',
    phone text NOT NULL DEFAULT '3584302024',
    phone_formatted text NOT NULL DEFAULT '+54 358 430-2024',
    email text NOT NULL DEFAULT 'enzogirardi84@gmail.com',
    location text NOT NULL DEFAULT 'Río Cuarto / Córdoba • Envíos e Instalación a todo el país',
    whatsapp_message text NOT NULL DEFAULT 'Hola Enzo! Vi tus programas a medida y quisiera consultar por un sistema personalizado para mi negocio.',
    main_services text[] NOT NULL DEFAULT ARRAY[]::text[],
    key_benefits text[] NOT NULL DEFAULT ARRAY[]::text[],
    promo_badge text NOT NULL DEFAULT '🔥 ¡DEMO GRATUITA Y ASESORAMIENTO SIN CARGO! 🔥',
    guarantee_text text NOT NULL DEFAULT 'Garantía total de satisfacción + Instalación y capacitación guiada',
    qr_url text NOT NULL DEFAULT 'https://wa.me/5493584302024?text=Hola%20Enzo!%20Me%20interesa%20un%20programa%20personalizado.',
    call_to_action text NOT NULL DEFAULT '¡ESCANEÁ EL QR O ESCRIBIME AHORA MISMO Y ACCEDÉ A TU DEMO!',
    updated_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Insertar configuración inicial por defecto (si no existe una)
INSERT INTO flyer_config (
    id, 
    developer_name, 
    role, 
    hook_title, 
    slogan, 
    phone, 
    phone_formatted, 
    email, 
    location, 
    whatsapp_message, 
    main_services, 
    key_benefits, 
    promo_badge, 
    guarantee_text, 
    qr_url, 
    call_to_action
) VALUES (
    1,
    'Enzo Girardi',
    'Programador & Desarrollador de Software',
    '¿LENTITUD EN TU NEGOCIO? MULTIPLICÁ TUS VENTAS HOY',
    'Desarrollo programas a medida que automatizan tu gestión, eliminan errores y ordenan tus ventas',
    '3584302024',
    '+54 358 430-2024',
    'enzogirardi84@gmail.com',
    'Río Cuarto / Córdoba • Envíos e Instalación a todo el país',
    'Hola Enzo! Vi tus programas a medida y quisiera consultar por un sistema personalizado para mi negocio.',
    ARRAY[
        'Sistemas de Gestión Gastronómica (Comandas, Mesas, Delivery)',
        'Historias Clínicas Digitales & Turnos para Salud y Consultorios',
        'Control de Stock e Inventario para Indumentaria y Calzado',
        'Puntos de Venta (POS) y Facturación Rápida en Caja',
        'ERP SaaS Multirrubro (Ferreterías, Talleres, Inmobiliarias)',
        'Reportes de Ventas e Ingresos Diarios en Tiempo Real'
    ],
    ARRAY[
        '100% Personalizado a la medida de tu negocio',
        'CERO Comisiones por venta ni cuotas abusivas',
        'Sistema ultra ágil: tus empleados aprenden en 10 minutos',
        'Soporte técnico directo con Enzo Girardi (Sin intermediarios)'
    ],
    '🔥 ¡DEMO GRATUITA Y ASESORAMIENTO SIN CARGO! 🔥',
    'Garantía total de satisfacción + Instalación y capacitación guiada',
    'https://wa.me/5493584302024?text=Hola%20Enzo!%20Me%20interesa%20un%20programa%20personalizado.',
    '¡ESCANEÁ EL QR O ESCRIBIME AHORA MISMO Y ACCEDÉ A TU DEMO!'
) ON CONFLICT (id) DO NOTHING;

-- 2. Tabla para registrar los Leads / Consultas de presupuesto
CREATE TABLE IF NOT EXISTS leads (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
    client_business text,
    client_contact text,
    industry text,
    selected_features text[],
    timeline text,
    notes text,
    estimated_days integer,
    status text DEFAULT 'nuevo'
);

-- Habilitar Row Level Security (RLS) en ambas tablas
ALTER TABLE flyer_config ENABLE ROW LEVEL SECURITY;
ALTER TABLE leads ENABLE ROW LEVEL SECURITY;

-- Políticas para flyer_config:
-- Permitir lectura pública
CREATE POLICY "Permitir lectura pública de flyer_config" ON flyer_config 
    FOR SELECT USING (true);

-- Permitir escritura pública (Para pruebas iniciales simplificadas. Recomendamos limitar en producción)
CREATE POLICY "Permitir escritura pública de flyer_config" ON flyer_config 
    FOR ALL USING (true) WITH CHECK (true);

-- Políticas para leads:
-- Permitir que cualquiera cree un lead
CREATE POLICY "Permitir inserción pública de leads" ON leads 
    FOR INSERT WITH CHECK (true);

-- Permitir lectura a todos (Para simplicidad del portafolio. Recomendamos cambiar a 'authenticated' en producción)
CREATE POLICY "Permitir lectura pública de leads" ON leads 
    FOR SELECT USING (true);
